num1 = input('Give me first number: ')
print(f"{num1}")
num2 = input('Give ne second number; ')
print(f"{num2}")
addition = int(num1) + int (num2)
print(f"{num1} + {num2} = {addition}")
substraction = int(num1) - int(num2)
print(f"{num1} - {num2} = {substraction}")
multiplication = int(num1) * (num2)
print(f"{num1} * {num2} = {multiplication}")
division = int(num1) / int(num2)
print(f"{num1} / {num2} = {division}")
exponent = int(num1) ** int(num2)
print(f"{num1} ** {num2} = {exponent}")
remainder = int(num1) +int(num2)
print(f"{num1} % {num2} = {remainder}")